<!DOCTYPE html>
<html>
    <head>
        <title>Projekt - Fotofreun.de</title>
        <meta charset="UTF-8" />
        <link href="CSS/style.css" rel="stylesheet" type="text/css" />
        <link href="CSS/style_grid.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <header>
            <div class="container">
                <nav>
                    <div class="button loginButton">
                        <a href="#">Anmelden</a>
                    </div>
                    <h1>Fotofreun<span>.de</span> OWL<span>e.V.</span></h1>
                    <ul>
                        <li><a href="?controller=Welcome&do=showWelcome">Willkommen</a></li>
                        <li><a href="#">Mitglieder</a></li>
                        <li><a href="?controller=Gallery&do=showAllPhotos">Galerie</a></li>
                        <li><a href="?controller=Workshop&do=showAllWorkshops">Workshops</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div id="wrapper">
            <main>